<script setup>
import { computed, onMounted, ref } from 'vue';
import { Bell, House, Images, LayoutDashboard, MapPin, MessagesSquare, Search, Settings, Stethoscope } from '@lucide/vue';

const api = import.meta.env.VITE_API_URL || '';
const token = ref(localStorage.getItem('saintia_admin_token') || '');
const section = ref('overview');
const loading = ref(false);
const toast = ref('');
const searchQuery = ref('');
const draggingDoctor = ref(null);
const dragOverDoctor = ref(null);
const expandedMessage = ref(null);
const previewDoctor = ref(null);
const content = ref({});
const submissions = ref([]);
const uploadedMedia = ref([]);
const staticMedia = [
  ...['张文凯-1','李琦-1','杨明-1','王强-1','田光辉-1','董磊-1','西会会-1','魏少魁-1'].map(name => `/圣娅医院素材/医生/中英版本/${name}.png`),
  ...['095719_719','095728_361','095733_673','095738_947','095742_997','095747_566','095751_686','095756_088','095800_247','095803_930','095807_894','095811_886','095815_993','095819_695'].map(id => `/圣娅医院素材/环境/Weixin Image_2026-08-21_${id}.jpg`),
  ...['095505_258','095516_434','095521_471','095527_061','095532_719'].map(id => `/圣娅医院素材/Weixin Videos2026-08-21_${id}.mp4`),
  '/圣娅医院素材/视频/Weixin Videos2026-08-21_095537_672.mp4',
];
const doctors = ref([]);
const nav = [{ id: 'overview', label: '工作台', note: '概览', icon: LayoutDashboard }, { id: 'home', label: '首页管理', note: 'Banner · 环境 · 视频', icon: House }, { id: 'doctors', label: '医生介绍', note: '团队信息与排序', icon: Stethoscope }, { id: 'contact', label: '联系我们', note: '地址 · 表单 · 地图', icon: MapPin }, { id: 'media', label: '素材库', note: '图片与视频', icon: Images }, { id: 'messages', label: '咨询记录', note: '用户提交信息', icon: MessagesSquare }, { id: 'settings', label: '站点设置', note: '基础信息', icon: Settings }];
const current = computed(() => nav.find(item => item.id === section.value));
const unreadCount = computed(() => submissions.value.filter(item => item.status === 'unread').length);
const filteredSubmissions = computed(() => { const query = searchQuery.value.trim().toLowerCase(); if (!query) return submissions.value; return submissions.value.filter(item => [item.name, item.phone, item.message].some(value => String(value || '').toLowerCase().includes(query))); });
const authHeaders = () => token.value ? { 'x-admin-token': token.value } : {};
function notify(message) { if (message === '医生资料模块已保存') { saveDoctors(); return; } toast.value = message; setTimeout(() => { toast.value = ''; }, 2800); }
async function request(path, options = {}) { const response = await fetch(`${api}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...authHeaders(), ...(options.headers || {}) } }); if (!response.ok) throw new Error((await response.json().catch(() => ({}))).error || '请求失败'); return response.json(); }
async function uploadAsset(file, onUploaded) { if (!file) return; const formData = new FormData(); formData.append('file', file); try { const result = await fetch(`${api}/api/admin/upload`, { method: 'POST', headers: authHeaders(), body: formData }); if (!result.ok) throw new Error((await result.json().catch(() => ({}))).error || '素材上传失败'); const uploaded = await result.json(); onUploaded(uploaded.url); uploadedMedia.value = [uploaded, ...uploadedMedia.value.filter((item) => item.url !== uploaded.url)]; notify('素材上传成功'); } catch (error) { notify(error.message); } }
async function uploadFromInput(event, onUploaded) { await uploadAsset(event.target.files?.[0], onUploaded); event.target.value = ''; }
async function uploadMediaFiles(event) { const files = [...(event.target.files || [])]; for (const file of files) await uploadAsset(file, (url) => uploadedMedia.value = [{ url, name: file.name, type: file.type.startsWith('video/') ? 'video' : 'image' }, ...uploadedMedia.value]); event.target.value = ''; }
async function load() { loading.value = true; try { content.value = await request('/api/content'); submissions.value = await request('/api/admin/contact-submissions'); doctors.value = await request('/api/admin/doctors'); uploadedMedia.value = await request('/api/admin/uploads'); } catch (error) { notify(error.message); } finally { loading.value = false; } }
async function saveContent() { try { await request('/api/admin/content', { method: 'PUT', body: JSON.stringify(content.value) }); notify('内容已发布，前端将自动读取最新版本'); } catch (error) { notify(error.message); } }
async function saveDoctors() { try { await request('/api/admin/doctors', { method: 'PUT', body: JSON.stringify(doctors.value) }); notify('医生资料已保存并同步'); } catch (error) { notify(error.message); } }
function addDoctor() { doctors.value.push({ name: '', nameEn: '', title: '', titleEn: '', focus: '', focusEn: '', bio: '', credentials: '', specialties: '', philosophy: '', image: '', enabled: true }); }
function removeDoctor(index) { if (window.confirm(`确定删除${doctors.value[index].name || '这位医生'}吗？`)) doctors.value.splice(index, 1); }
function openDoctorPreview(doctor) { if (doctor.image) previewDoctor.value = doctor; }
async function markRead(item) { await request(`/api/admin/contact-submissions/${item.id}`, { method: 'PATCH', body: JSON.stringify({ status: 'read' }) }); item.status = 'read'; notify('已标记为已读'); }
function saveToken() { localStorage.setItem('saintia_admin_token', token.value); notify('管理员凭证已保存'); load(); }
function mediaItems() { return Array.from(new Set([content.value.heroImage, content.value.heroVideo, ...staticMedia, ...uploadedMedia.value.map((item) => item.url)].filter(Boolean))); }
function relativeTime(value) { const timestamp = new Date(String(value).replace(' ', 'T')).getTime(); if (!Number.isFinite(timestamp)) return value; const seconds = Math.max(0, Math.floor((Date.now() - timestamp) / 1000)); if (seconds < 60) return '刚刚'; if (seconds < 3600) return `${Math.floor(seconds / 60)}分钟前`; if (seconds < 86400) return `${Math.floor(seconds / 3600)}小时前`; if (seconds < 604800) return `${Math.floor(seconds / 86400)}天前`; return new Date(timestamp).toLocaleDateString('zh-CN'); }
function startDoctorDrag(index) { draggingDoctor.value = index; }
function overDoctor(index) { dragOverDoctor.value = index; }
function dropDoctor(index) { if (draggingDoctor.value === null || draggingDoctor.value === index) return; const next = [...doctors.value]; const [moved] = next.splice(draggingDoctor.value, 1); next.splice(index, 0, moved); doctors.value = next; draggingDoctor.value = null; dragOverDoctor.value = null; notify('医生顺序已调整，请点击保存排序'); }
function endDoctorDrag() { draggingDoctor.value = null; dragOverDoctor.value = null; }
onMounted(load);
</script>
<template>
  <div class="app-shell">
    <aside class="sidebar">
      <div class="brand"><span>圣娅</span><small>SAINTIA MEDICAL CENTER</small></div>
      <div class="side-label">内容管理</div>
      <button v-for="item in nav" :key="item.id" class="nav-item" :class="{ active: section === item.id }" :aria-current="section === item.id ? 'page' : undefined" @click="section = item.id"><span class="nav-mark"><component :is="item.icon" :size="18" :stroke-width="1.7" /></span><span><strong>{{ item.label }}</strong><small>{{ item.note }}</small></span><b v-if="item.id === 'messages' && unreadCount">{{ unreadCount }}</b></button>
      <div class="sidebar-bottom"><span class="status-dot"></span> 内容服务正常</div>
    </aside>
    <main class="main-area">
      <header class="topbar"><div><p class="eyebrow">内容管理 / {{ current.label }}</p><h1>{{ current.label }}</h1></div><div class="top-actions"><label class="admin-search"><Search :size="16" /><input v-model="searchQuery" placeholder="搜索咨询、姓名或电话" @focus="section = 'messages'" /></label><button class="notice-button" aria-label="查看未读咨询" @click="section = 'messages'"><Bell :size="18" /><b v-if="unreadCount">{{ unreadCount }}</b></button><span class="saved-state"><i></i> 已连接</span><button class="avatar" aria-label="管理员账户">管</button></div></header>
      <div v-if="toast" class="toast">{{ toast }}</div>
      <section v-if="section === 'overview'" class="content-view"><div class="welcome"><div><p class="eyebrow">GOOD MORNING</p><h2>今天也让每一次访问都更安心。</h2><p>从这里管理圣娅官网的每一处文字、图片、视频与咨询信息。</p></div><div class="welcome-orb">SY</div></div><div class="metric-grid"><article><span>未读咨询</span><strong>{{ submissions.filter(x => x.status === 'unread').length }}</strong><small>需要及时跟进</small></article><article><span>医生团队</span><strong>{{ doctors.length }}</strong><small>已配置医生资料</small></article><article><span>首页内容</span><strong>12</strong><small>可编辑内容区块</small></article><article><span>媒体素材</span><strong>{{ mediaItems().length }}</strong><small>正在使用的文件</small></article></div><div class="two-panels"><article class="panel"><div class="panel-head"><div><p class="eyebrow">QUICK ACCESS</p><h3>快速编辑</h3></div></div><div class="quick-list"><button @click="section = 'home'">首页首屏与视频 <span>→</span></button><button @click="section = 'doctors'">医生团队信息 <span>→</span></button><button @click="section = 'contact'">联系方式与地图 <span>→</span></button></div></article><article class="panel"><div class="panel-head"><div><p class="eyebrow">LATEST</p><h3>最近咨询</h3></div><button class="text-button" @click="section = 'messages'">查看全部</button></div><div v-if="submissions.length" class="latest-item" v-for="item in submissions.slice(0, 3)" :key="item.id"><span class="latest-avatar">{{ item.name.slice(0,1) }}</span><div><strong>{{ item.name }}</strong><p>{{ item.message }}</p></div><time>{{ item.created_at }}</time></div><div v-else class="empty">暂无咨询记录</div></article></div></section>
      <section v-else-if="section === 'home'" class="content-view"><div class="page-intro"><div><p class="eyebrow">HOME PAGE</p><h2>首页内容</h2><p>编辑首屏视觉和医院品牌主张，保存后前端自动同步。</p></div><button class="primary" @click="saveContent">发布更改</button></div><div class="editor-grid"><article class="panel form-panel"><div class="panel-head"><h3>首屏视觉</h3><span class="tag">LIVE</span></div><label>品牌主张（中文）<input v-model="content.tagline" /></label><label>品牌主张（English）<input v-model="content.taglineEn" /></label><label>首屏图片<input v-model="content.heroImage" placeholder="可上传或填写路径" /><input class="file-input" type="file" accept="image/*" @change="uploadFromInput($event, (url) => content.heroImage = url)" /></label><label>首页视频<input v-model="content.heroVideo" placeholder="可上传或填写路径" /><input class="file-input" type="file" accept="video/*" @change="uploadFromInput($event, (url) => content.heroVideo = url)" /></label><div class="preview-media"><img :src="content.heroImage" alt="首屏预览" /><span>首页首屏预览</span></div></article><article class="panel"><div class="panel-head"><h3>页面结构</h3></div><div class="section-list"><div><b>01</b><span>医院概览<small>简介 · 数据指标</small></span><em>已启用</em></div><div><b>02</b><span>医院环境<small>环境图集</small></span><em>已启用</em></div><div><b>03</b><span>安全与服务<small>六重保障</small></span><em>已启用</em></div><div><b>04</b><span>医生团队<small>精选医生</small></span><em>已启用</em></div><div><b>05</b><span>医院视频<small>宣传视频</small></span><em>已启用</em></div></div></article></div></section>
      <section v-else-if="section === 'doctors'" class="content-view"><div class="page-intro"><div><p class="eyebrow">DOCTORS</p><h2>医生介绍</h2><p>维护医生公开资料。图片按原海报比例完整展示，详细资历与擅长项目可在此同步修改。</p></div><div class="page-actions"><button class="secondary" @click="addDoctor">新增医生</button><button class="primary" @click="saveDoctors">保存更改</button></div></div><article class="panel table-panel doctors-table-panel"><table><thead><tr><th>排序</th><th>照片</th><th>中文姓名</th><th>英文姓名</th><th>中文职称</th><th>英文职称</th><th>中文专业方向</th><th>英文专业方向</th><th>简介</th><th>资历 / 任职（每行一项）</th><th>擅长项目（每行一项）</th><th>图片</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="(doctor, index) in doctors" :key="doctor.id || `new-${index}`" draggable="true" :class="{ dragging: draggingDoctor === index, 'drag-over': dragOverDoctor === index && draggingDoctor !== index }" @dragstart="startDoctorDrag(index)" @dragover.prevent="overDoctor(index)" @drop.prevent="dropDoctor(index)" @dragend="endDoctorDrag"><td class="drag-handle">☷<small>#{{ String(index + 1).padStart(2, '0') }}</small></td><td><button class="doctor-photo-button" type="button" :aria-label="`放大查看${doctor.name || '医生'}照片`" @click.stop="openDoctorPreview(doctor)"><img class="doctor-table-image" :src="doctor.image" :alt="doctor.name || '医生照片'" /><span>查看</span></button></td><td><input v-model="doctor.name" placeholder="必填" /></td><td><input v-model="doctor.nameEn" /></td><td><input v-model="doctor.title" placeholder="必填" /></td><td><input v-model="doctor.titleEn" /></td><td><textarea v-model="doctor.focus" /></td><td><textarea v-model="doctor.focusEn" /></td><td><textarea v-model="doctor.bio" placeholder="简介" /></td><td><textarea v-model="doctor.credentials" placeholder="每行一项" /></td><td><textarea v-model="doctor.specialties" placeholder="每行一项" /></td><td><input v-model="doctor.image" placeholder="路径或 URL" /><input class="file-input" type="file" accept="image/*" @change="uploadFromInput($event, (url) => doctor.image = url)" /></td><td><button class="toggle" :class="{ on: doctor.enabled }" :aria-pressed="doctor.enabled" @click="doctor.enabled = !doctor.enabled"><i></i>{{ doctor.enabled ? '展示中' : '已隐藏' }}</button></td><td><button class="text-button danger-button" @click="removeDoctor(index)">删除</button></td></tr></tbody></table><div v-if="!doctors.length" class="empty">暂无医生，请点击“新增医生”添加</div></article></section>
      <section v-else-if="section === 'contact'" class="content-view"><div class="page-intro"><div><p class="eyebrow">CONTACT PAGE</p><h2>联系我们</h2><p>维护医院地址、电话、邮箱和接诊时间。</p></div><button class="primary" @click="saveContent">发布更改</button></div><article class="panel form-panel contact-editor"><div class="panel-head"><h3>联系信息</h3><span class="tag">PUBLIC</span></div><div class="form-two"><label>医院名称（中文）<input v-model="content.siteName" /></label><label>医院名称（English）<input v-model="content.siteNameEn" /></label><label>联系电话<input v-model="content.phone" /></label><label>邮箱<input v-model="content.email" /></label><label>营业时间（中文）<input v-model="content.hours" /></label><label>营业时间（English）<input v-model="content.hoursEn" /></label></div><label>医院地址（中文）<input v-model="content.address" /></label><label>医院地址（English）<input v-model="content.addressEn" /></label><label>地图链接<input v-model="content.mapUrl" placeholder="https://maps.google.com/..." /></label><div class="contact-preview"><span>当前前端展示</span><strong>{{ content.address }}</strong><p>{{ content.hours }} · {{ content.phone }}</p></div></article></section>
      <section v-else-if="section === 'media'" class="content-view"><div class="page-intro"><div><p class="eyebrow">MEDIA LIBRARY</p><h2>素材库</h2><p>上传后的素材会保存到网站素材目录，可用于首页、医生和其他内容模块。</p></div><label class="upload-button secondary">上传图片 / 视频<input class="visually-hidden" type="file" accept="image/*,video/*" multiple @change="uploadMediaFiles" /></label></div><div class="media-grid"><article class="media-card" v-for="(item, index) in mediaItems()" :key="item"><div class="media-thumb" :class="{ video: item.endsWith('.mp4') || item.endsWith('.webm') || item.endsWith('.mov') }"><video v-if="item.endsWith('.mp4') || item.endsWith('.webm') || item.endsWith('.mov')" :src="item" muted controls></video><img v-else :src="item" alt="素材" /><span>{{ item.endsWith('.mp4') || item.endsWith('.webm') || item.endsWith('.mov') ? 'VIDEO' : 'IMAGE' }}</span></div><p>{{ item.split('/').pop() }}</p><small>素材 {{ index + 1 }}</small></article></div></section>
      <section v-else-if="section === 'messages'" class="content-view"><div class="page-intro"><div><p class="eyebrow">INBOX</p><h2>咨询记录</h2><p>查看前端联系表单提交的信息，点击咨询内容可展开全文。</p></div><button class="secondary" @click="load">刷新记录</button></div><article class="panel table-panel"><table><thead><tr><th>状态</th><th>提交时间</th><th>称呼</th><th>联系电话</th><th>咨询内容</th><th>操作</th></tr></thead><tbody><tr v-for="item in filteredSubmissions" :key="item.id"><td><span class="status-pill" :class="item.status">{{ item.status === 'read' ? '已读' : '未读' }}</span></td><td><time :title="item.created_at">{{ relativeTime(item.created_at) }}</time></td><td><strong>{{ item.name }}</strong></td><td>{{ item.phone }}</td><td class="message-cell" :class="{ expanded: expandedMessage === item.id }" :title="item.message" role="button" tabindex="0" @click="expandedMessage = expandedMessage === item.id ? null : item.id" @keydown.enter.prevent="expandedMessage = expandedMessage === item.id ? null : item.id" @keydown.space.prevent="expandedMessage = expandedMessage === item.id ? null : item.id">{{ item.message }}</td><td><button v-if="item.status === 'unread'" class="text-button" @click="markRead(item)">标记已读</button><span v-else class="muted">已处理</span></td></tr></tbody></table><div v-if="!filteredSubmissions.length" class="empty">{{ searchQuery ? '没有匹配的咨询记录' : '还没有用户咨询记录' }}</div></article></section>
      <section v-else class="content-view"><div class="page-intro"><div><p class="eyebrow">SITE SETTINGS</p><h2>站点设置</h2><p>统一维护医院品牌基础信息。</p></div><button class="primary" @click="saveContent">保存设置</button></div><article class="panel form-panel"><div class="panel-head"><h3>品牌与联系方式</h3></div><div class="form-two"><label>医院名称（中文）<input v-model="content.siteName" /></label><label>医院名称（English）<input v-model="content.siteNameEn" /></label><label>品牌主张（中文）<input v-model="content.tagline" /></label><label>品牌主张（English）<input v-model="content.taglineEn" /></label><label>联系电话<input v-model="content.phone" /></label><label>邮箱<input v-model="content.email" /></label></div><label>管理员 Token<input v-model="token" type="password" placeholder="生产环境建议设置 ADMIN_TOKEN" /><button class="secondary token-button" @click="saveToken">保存凭证</button></label></article></section>
    </main>
    <div v-if="previewDoctor" class="doctor-preview-backdrop" role="presentation" @click="previewDoctor = null"><div class="doctor-preview-dialog" role="dialog" aria-modal="true" :aria-label="`${previewDoctor.name || '医生'}照片预览`" @click.stop><button class="doctor-preview-close" type="button" aria-label="关闭照片预览" @click="previewDoctor = null">×</button><img :src="previewDoctor.image" :alt="previewDoctor.name || '医生照片'" /><p>{{ previewDoctor.name || '医生照片' }}</p></div></div>
  </div>
</template>
