<script setup>
import { computed, onMounted, ref } from 'vue';

const api = import.meta.env.VITE_API_URL || '';
const token = ref(localStorage.getItem('saintia_admin_token') || '');
const section = ref('overview');
const loading = ref(false);
const toast = ref('');
const content = ref({});
const submissions = ref([]);
const doctors = ref([
  { name: '牛勇敢', title: '院长 / 主任医师', focus: '整形外科、面部年轻化', image: '/圣娅医院素材/医生/Weixin Image_2026-08-21_095542_340.jpg', enabled: true },
  { name: '余东', title: '副主任医师', focus: '美容外科、眼部整形', image: '/圣娅医院素材/医生/Weixin Image_2026-08-21_095546_385.jpg', enabled: true },
  { name: '齐金杰', title: '主治医师', focus: '鼻部整形、轮廓美学', image: '/圣娅医院素材/医生/Weixin Image_2026-08-21_095549_945.jpg', enabled: true },
]);
const nav = [{ id: 'overview', label: '工作台', note: '概览' }, { id: 'home', label: '首页管理', note: 'Banner · 环境 · 视频' }, { id: 'doctors', label: '医生介绍', note: '团队信息与排序' }, { id: 'contact', label: '联系我们', note: '地址 · 表单 · 地图' }, { id: 'media', label: '素材库', note: '图片与视频' }, { id: 'messages', label: '咨询记录', note: '用户提交信息' }, { id: 'settings', label: '站点设置', note: '基础信息' }];
const current = computed(() => nav.find(item => item.id === section.value));
const authHeaders = () => token.value ? { 'x-admin-token': token.value } : {};
function notify(message) { if (message === '医生资料模块已保存') { saveDoctors(); return; } toast.value = message; setTimeout(() => { toast.value = ''; }, 2800); }
async function request(path, options = {}) { const response = await fetch(`${api}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...authHeaders(), ...(options.headers || {}) } }); if (!response.ok) throw new Error((await response.json().catch(() => ({}))).error || '请求失败'); return response.json(); }
async function load() { loading.value = true; try { content.value = await request('/api/content'); submissions.value = await request('/api/admin/contact-submissions'); const remoteDoctors = await request('/api/doctors'); if (remoteDoctors.length) doctors.value = remoteDoctors; } catch (error) { notify(error.message); } finally { loading.value = false; } }
async function saveContent() { try { await request('/api/admin/content', { method: 'PUT', body: JSON.stringify(content.value) }); notify('内容已发布，前端将自动读取最新版本'); } catch (error) { notify(error.message); } }
async function saveDoctors() { try { await request('/api/admin/doctors', { method: 'PUT', body: JSON.stringify(doctors.value) }); notify('医生资料已保存并同步'); } catch (error) { notify(error.message); } }
async function markRead(item) { await request(`/api/admin/contact-submissions/${item.id}`, { method: 'PATCH', body: JSON.stringify({ status: 'read' }) }); item.status = 'read'; notify('已标记为已读'); }
function saveToken() { localStorage.setItem('saintia_admin_token', token.value); notify('管理员凭证已保存'); load(); }
function mediaItems() { return [content.value.heroImage, content.value.heroVideo].filter(Boolean); }
onMounted(load);
</script>
<template>
  <div class="app-shell">
    <aside class="sidebar">
      <div class="brand"><span>圣娅</span><small>SAINTIA MEDICAL CENTER</small></div>
      <div class="side-label">内容管理</div>
      <button v-for="item in nav" :key="item.id" class="nav-item" :class="{ active: section === item.id }" @click="section = item.id"><span class="nav-mark">{{ item.id === 'overview' ? '⌂' : item.id === 'home' ? '◈' : item.id === 'doctors' ? '◌' : item.id === 'contact' ? '⌖' : item.id === 'media' ? '▧' : item.id === 'messages' ? '✉' : '⚙' }}</span><span><strong>{{ item.label }}</strong><small>{{ item.note }}</small></span><b v-if="item.id === 'messages' && submissions.filter(x => x.status === 'unread').length">{{ submissions.filter(x => x.status === 'unread').length }}</b></button>
      <div class="sidebar-bottom"><span class="status-dot"></span> 内容服务正常</div>
    </aside>
    <main class="main-area">
      <header class="topbar"><div><p class="eyebrow">SAINTIA / ADMIN</p><h1>{{ current.label }}</h1></div><div class="top-actions"><span class="saved-state"><i></i> 已连接</span><button class="avatar">管</button></div></header>
      <div v-if="toast" class="toast">{{ toast }}</div>
      <section v-if="section === 'overview'" class="content-view"><div class="welcome"><div><p class="eyebrow">GOOD MORNING</p><h2>今天也让每一次访问都更安心。</h2><p>从这里管理圣娅官网的每一处文字、图片、视频与咨询信息。</p></div><div class="welcome-orb">SY</div></div><div class="metric-grid"><article><span>未读咨询</span><strong>{{ submissions.filter(x => x.status === 'unread').length }}</strong><small>需要及时跟进</small></article><article><span>医生团队</span><strong>{{ doctors.length }}</strong><small>已配置医生资料</small></article><article><span>首页内容</span><strong>12</strong><small>可编辑内容区块</small></article><article><span>媒体素材</span><strong>{{ mediaItems().length }}</strong><small>正在使用的文件</small></article></div><div class="two-panels"><article class="panel"><div class="panel-head"><div><p class="eyebrow">QUICK ACCESS</p><h3>快速编辑</h3></div></div><div class="quick-list"><button @click="section = 'home'">首页首屏与视频 <span>→</span></button><button @click="section = 'doctors'">医生团队信息 <span>→</span></button><button @click="section = 'contact'">联系方式与地图 <span>→</span></button></div></article><article class="panel"><div class="panel-head"><div><p class="eyebrow">LATEST</p><h3>最近咨询</h3></div><button class="text-button" @click="section = 'messages'">查看全部</button></div><div v-if="submissions.length" class="latest-item" v-for="item in submissions.slice(0, 3)" :key="item.id"><span class="latest-avatar">{{ item.name.slice(0,1) }}</span><div><strong>{{ item.name }}</strong><p>{{ item.message }}</p></div><time>{{ item.created_at }}</time></div><div v-else class="empty">暂无咨询记录</div></article></div></section>
      <section v-else-if="section === 'home'" class="content-view"><div class="page-intro"><div><p class="eyebrow">HOME PAGE</p><h2>首页内容</h2><p>编辑首屏视觉和医院品牌主张，保存后前端自动同步。</p></div><button class="primary" @click="saveContent">发布更改</button></div><div class="editor-grid"><article class="panel form-panel"><div class="panel-head"><h3>首屏视觉</h3><span class="tag">LIVE</span></div><label>品牌主张<input v-model="content.tagline" /></label><label>首屏图片 URL<input v-model="content.heroImage" /></label><label>首页视频 URL<input v-model="content.heroVideo" /></label><div class="preview-media"><img :src="content.heroImage" alt="首屏预览" /><span>首页首屏预览</span></div></article><article class="panel"><div class="panel-head"><h3>页面结构</h3></div><div class="section-list"><div><b>01</b><span>医院概览<small>简介 · 数据指标</small></span><em>已启用</em></div><div><b>02</b><span>医院环境<small>环境图集</small></span><em>已启用</em></div><div><b>03</b><span>安全与服务<small>六重保障</small></span><em>已启用</em></div><div><b>04</b><span>医生团队<small>精选医生</small></span><em>已启用</em></div><div><b>05</b><span>医院视频<small>宣传视频</small></span><em>已启用</em></div></div></article></div></section>
      <section v-else-if="section === 'doctors'" class="content-view"><div class="page-intro"><div><p class="eyebrow">DOCTORS</p><h2>医生介绍</h2><p>管理医生姓名、职称、擅长方向与展示图片。</p></div><button class="primary" @click="notify('医生资料模块已保存')">保存排序</button></div><div class="doctor-admin-grid"><article class="doctor-admin-card" v-for="(doctor, index) in doctors" :key="doctor.name"><div class="doctor-image"><img :src="doctor.image" :alt="doctor.name" /><span>#{{ String(index + 1).padStart(2, '0') }}</span></div><div class="doctor-fields"><label>姓名<input v-model="doctor.name" /></label><label>职称<input v-model="doctor.title" /></label><label>专业方向<input v-model="doctor.focus" /></label><label>图片 URL<input v-model="doctor.image" /></label><button class="toggle" :class="{ on: doctor.enabled }" @click="doctor.enabled = !doctor.enabled"><i></i>{{ doctor.enabled ? '前端展示中' : '已隐藏' }}</button></div></article></div></section>
      <section v-else-if="section === 'contact'" class="content-view"><div class="page-intro"><div><p class="eyebrow">CONTACT PAGE</p><h2>联系我们</h2><p>维护医院地址、电话、邮箱和接诊时间。</p></div><button class="primary" @click="saveContent">发布更改</button></div><article class="panel form-panel contact-editor"><div class="panel-head"><h3>联系信息</h3><span class="tag">PUBLIC</span></div><div class="form-two"><label>医院名称<input v-model="content.siteName" /></label><label>联系电话<input v-model="content.phone" /></label><label>邮箱<input v-model="content.email" /></label><label>营业时间<input v-model="content.hours" /></label></div><label>医院地址<input v-model="content.address" /></label><label>地图链接<input v-model="content.mapUrl" placeholder="https://maps.google.com/..." /></label><div class="contact-preview"><span>当前前端展示</span><strong>{{ content.address }}</strong><p>{{ content.hours }} · {{ content.phone }}</p></div></article></section>
      <section v-else-if="section === 'media'" class="content-view"><div class="page-intro"><div><p class="eyebrow">MEDIA LIBRARY</p><h2>素材库</h2><p>当前页面使用的图片和视频。替换 URL 后点击发布即可同步。</p></div></div><div class="media-grid"><article class="media-card" v-for="(item, index) in mediaItems()" :key="item"><div class="media-thumb" :class="{ video: item.endsWith('.mp4') }"><video v-if="item.endsWith('.mp4')" :src="item" muted></video><img v-else :src="item" alt="素材" /><span>{{ item.endsWith('.mp4') ? 'VIDEO' : 'IMAGE' }}</span></div><p>{{ item.split('/').pop() }}</p><small>首页使用 · 素材 {{ index + 1 }}</small></article></div></section>
      <section v-else-if="section === 'messages'" class="content-view"><div class="page-intro"><div><p class="eyebrow">INBOX</p><h2>咨询记录</h2><p>查看前端联系表单提交的信息，跟进每一位来访者。</p></div><button class="secondary" @click="load">刷新记录</button></div><article class="panel table-panel"><table><thead><tr><th>状态</th><th>提交时间</th><th>称呼</th><th>联系电话</th><th>咨询内容</th><th>操作</th></tr></thead><tbody><tr v-for="item in submissions" :key="item.id"><td><span class="status-pill" :class="item.status">{{ item.status === 'read' ? '已读' : '未读' }}</span></td><td>{{ item.created_at }}</td><td><strong>{{ item.name }}</strong></td><td>{{ item.phone }}</td><td class="message-cell">{{ item.message }}</td><td><button v-if="item.status === 'unread'" class="text-button" @click="markRead(item)">标记已读</button><span v-else class="muted">已处理</span></td></tr></tbody></table><div v-if="!submissions.length" class="empty">还没有用户咨询记录</div></article></section>
      <section v-else class="content-view"><div class="page-intro"><div><p class="eyebrow">SITE SETTINGS</p><h2>站点设置</h2><p>统一维护医院品牌基础信息。</p></div><button class="primary" @click="saveContent">保存设置</button></div><article class="panel form-panel"><div class="panel-head"><h3>品牌与联系方式</h3></div><div class="form-two"><label>医院名称<input v-model="content.siteName" /></label><label>品牌主张<input v-model="content.tagline" /></label><label>联系电话<input v-model="content.phone" /></label><label>邮箱<input v-model="content.email" /></label></div><label>管理员 Token<input v-model="token" type="password" placeholder="生产环境建议设置 ADMIN_TOKEN" /><button class="secondary token-button" @click="saveToken">保存凭证</button></label></article></section>
    </main>
  </div>
</template>
