'use client';
import Image from 'next/image';
import Link from 'next/link';
import { useLanguage } from './LanguageProvider';
const departments = [
  { title: '美容外科', titleEn: 'Aesthetic Surgery', english: 'AESTHETIC', description: '以审美与安全为前提，提供个性化的美容外科与皮肤管理服务。', descriptionEn: 'Personalized aesthetic surgery and skin care founded on safety and considered aesthetics.', image: '/ribenpeizhen/1715130456185169.jpg' },
  { title: '美容皮肤科', titleEn: 'Aesthetic Dermatology', english: 'DERMATOLOGY', description: '关注皮肤状态与长期管理，让每一次咨询都有清晰的依据。', descriptionEn: 'Evidence-led consultations focused on skin health and long-term care.', image: '/ribenpeizhen/1715131568213192.jpg' },
  { title: '医疗健康管理', titleEn: 'Health Management', english: 'WELLNESS', description: '从体检、咨询到持续管理，帮助您更好地了解自己的身体。', descriptionEn: 'From screening to ongoing support, we help you understand and manage your health.', image: '/ribenpeizhen/1715131691832026.jpg' },
];
export function DepartmentCards() { const { language, text } = useLanguage(); return <section className="sy-departments" data-reveal><div className="sy-container"><div className="sy-departments-heading"><div><p className="sy-kicker">OUR DEPARTMENTS</p><h2>{text('一个团队，三种专业视角', 'One team, three perspectives')}</h2></div><p>{text('从外在美学到整体健康，我们把专业服务放在同一套安心标准里。', 'From personal aesthetics to whole-body wellness, every service follows the same trusted standards.')}</p></div><div className="weui-cells sy-department-grid" data-stagger>{departments.map((item) => { const title = language === 'zh' ? item.title : item.titleEn; return <article className="weui-cell" key={item.title}><div className="sy-department-image"><Image src={item.image} alt={title} fill sizes="(max-width: 700px) 100vw, 33vw" /></div><div className="sy-department-copy"><p>{item.english}</p><h3>{title}</h3><span>{language === 'zh' ? item.description : item.descriptionEn}</span><Link href="/contact">{text('了解更多', 'Learn More')} <b>→</b></Link></div></article>; })}</div></div></section>; }
