FROM dockerproxy.net/library/node:24.14.0-bookworm-slim

WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
COPY --chown=node:node frontend-runtime/standalone ./
COPY --chown=node:node frontend-runtime/static ./.next/static
COPY --chown=node:node frontend-runtime/public ./public
USER node
EXPOSE 3000
CMD ["node", "server.js"]
